"""making changes

Revision ID: 1391f87a7114
Revises: 617eb3292145
Create Date: 2023-02-28 21:13:05.443959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1391f87a7114'
down_revision = '617eb3292145'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
