"""making changes

Revision ID: 171655b8df44
Revises: f8a1047d7597
Create Date: 2023-02-25 22:15:30.698037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171655b8df44'
down_revision = 'f8a1047d7597'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
