"""making changes

Revision ID: 1851d2b9a8bc
Revises: 6b66e1cb65e4
Create Date: 2023-03-01 21:54:39.287817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1851d2b9a8bc'
down_revision = '6b66e1cb65e4'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
