"""making changes

Revision ID: 2f984a005a83
Revises: e21f63fa95e9
Create Date: 2023-02-28 21:21:06.347024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f984a005a83'
down_revision = 'e21f63fa95e9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
