"""making changes

Revision ID: 3919c435162a
Revises: 8b919debccc9
Create Date: 2023-03-01 21:27:15.751811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3919c435162a'
down_revision = '8b919debccc9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
