"""making changes

Revision ID: 3dcde096735e
Revises: f21cb9e17461
Create Date: 2023-02-28 20:04:45.043951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcde096735e'
down_revision = 'f21cb9e17461'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
