"""making changes

Revision ID: 481675efcadf
Revises: 1851d2b9a8bc
Create Date: 2023-03-01 21:56:07.246282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481675efcadf'
down_revision = '1851d2b9a8bc'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
