"""making changes

Revision ID: 4995ad316fd1
Revises: ef7e98705672
Create Date: 2023-03-01 21:51:52.156021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4995ad316fd1'
down_revision = 'ef7e98705672'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
