"""making changes

Revision ID: 5e204673d15c
Revises: f67ad2c03219
Create Date: 2023-02-25 22:22:48.687722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e204673d15c'
down_revision = 'f67ad2c03219'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
