"""making changes

Revision ID: 617eb3292145
Revises: e001a9c5e2c6
Create Date: 2023-02-28 20:27:53.514864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617eb3292145'
down_revision = 'e001a9c5e2c6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
