"""making changes

Revision ID: 6b66e1cb65e4
Revises: 4995ad316fd1
Create Date: 2023-03-01 21:53:13.522445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b66e1cb65e4'
down_revision = '4995ad316fd1'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
