"""making changes

Revision ID: 6c59d20a33c0
Revises: a69c80221d99
Create Date: 2023-03-01 21:24:22.475614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c59d20a33c0'
down_revision = 'a69c80221d99'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
