"""making changes

Revision ID: 8b919debccc9
Revises: 6c59d20a33c0
Create Date: 2023-03-01 21:26:49.304962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b919debccc9'
down_revision = '6c59d20a33c0'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
