"""making changes

Revision ID: 90260465b836
Revises: a183649b6d69
Create Date: 2023-02-28 21:15:28.696653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90260465b836'
down_revision = 'a183649b6d69'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
