"""making changes

Revision ID: a183649b6d69
Revises: 1391f87a7114
Create Date: 2023-02-28 21:13:50.237337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a183649b6d69'
down_revision = '1391f87a7114'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
