"""making changes

Revision ID: a4dd1cb5b2ca
Revises: 481675efcadf
Create Date: 2023-03-01 23:37:56.800861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dd1cb5b2ca'
down_revision = '481675efcadf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
