"""making changes

Revision ID: e21f63fa95e9
Revises: ee39e5167446
Create Date: 2023-02-28 21:21:03.540940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21f63fa95e9'
down_revision = 'ee39e5167446'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
