"""making changes

Revision ID: ef7e98705672
Revises: f6c0971bec3a
Create Date: 2023-03-01 21:40:01.785276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7e98705672'
down_revision = 'f6c0971bec3a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
