"""making changes

Revision ID: f21cb9e17461
Revises: f398b5bd0f6e
Create Date: 2023-02-28 19:54:24.905059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21cb9e17461'
down_revision = 'f398b5bd0f6e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
