"""making changes

Revision ID: f398b5bd0f6e
Revises: 7e5844a6ced5
Create Date: 2023-02-28 19:37:01.733302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f398b5bd0f6e'
down_revision = '7e5844a6ced5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
