"""making changes

Revision ID: f4fbcf46165f
Revises: a4dd1cb5b2ca
Create Date: 2023-03-01 23:38:00.205699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fbcf46165f'
down_revision = 'a4dd1cb5b2ca'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
