"""making changes

Revision ID: f67ad2c03219
Revises: 171655b8df44
Create Date: 2023-02-25 22:21:09.204816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67ad2c03219'
down_revision = '171655b8df44'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
