"""making changes

Revision ID: f6c0971bec3a
Revises: ddb875f0df6a
Create Date: 2023-03-01 21:30:31.933442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c0971bec3a'
down_revision = 'ddb875f0df6a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
